from .calculations import  *

context = {
    'Num_of_variant': 25,
    'R_n': R_n,
    'I_n': I_n,
    'U_ip_first': U_ip_first,
    'U_ip_second': U_ip_second,
    'U_ip_okrugl': U_ip_okrugl,
    'U_ke_max': U_ke_max,
    'I_k_max': I_k_max,
    'P_k_max_start': P_k_max_start,
    'K_z': K_z,
    'P_k_max': P_k_max,
    'T_p_dop': T_p_dop,
    'K_t': K_t,
    'R_t_kt': R_t_kt,
    'R_t_kc': R_t_kc,
    'T_s_v': T_s_v,
    'R_t_pk': R_t_pk,
    'K_z_new': K_z_new,
    'N_min_okrugl': N_min_okrugl,
    'N_max_okrugl': N_max_okrugl,
    'Q_1': Q_1,
    'P_rasseivaemaya': P_rasseivaemaya,
    'H': H,
    'D': D,
    'd_2': d_2,
    'H_2': H_2,
    'D_2': D_2

}

# --- Контекст для XML-парсинга (только формулы) ---
xml_replacements = {
    'Ukedop': U_ke_max,
    'Ikdop': I_k_max,
    'Pkdop': P_k_max_start,
    # 'betamin': betamin,
    'Pkmax': P_k_max,
    'Rtkc': R_t_kc,
    'Rtpk': R_t_pk,
    'Kznew': K_z_new,
    'Tpdop': T_p_dop,
    'Tsv': T_s_v,
    'Rtkt': R_t_kt,
    'Nmin': N_min,
    'Nmax': N_max,
    'Rtcdop': R_tc_dop,
    'Kt': K_t,
    'Qt': Q_t,
    'Q1': Q_1,
    **{f'QG{i+1}': QG_numbers[i] for i in range(30)},
    **{f'QTN{i+2}': QTN_numbers[i] for i in range(30)},
    'Nopt': x_cross,
    'Noptmin': N_opt_min,
    'QTNopt': QTN_opt,
    'Popt': P_opt,
    'Noptkon': N_opt_konechnoe,
    'QTNoptkon': QTN_optimal_konechoe,
    'Qosn': Q_osn,
    'Fp': F_p,
    'rekvcm': r_ekv_cm,
    'lambda': lambd_znach,
    'vd': d_2,
    'phi': phi_p,
    'ASH': H,
    'DI': D,
    'rLz': r_L_z,
    'gamma': gamma,
    'aef': a_ef,
    'ksi': ksi,
    'dzhi': g,
    'vi': v,
    'vis': v_s,
    'Ttmax': T_t_max,
    'Azn': A,
    'epr': eps_pr,
    'phione': phi_1,
    'phitwo': phi_2,
    'ak': a_k,
    'al': a_l,
    'asum': a_sum,
    'aefrad':a_ef_rad,
    'Sp':S_p,
    'bi': bi,
    'ci': ci,
    'nrebra':n_rebra,
    'hrebr': h_rebr,
    'Pkmaxnew': P_k_max_new,
    'Qosnnew': Q_osn_new,
    'Fpn': F_p_new,
    'rekvcmnew': r_ekv_cm_new,
    'phinew': phi_new,
    'ASHnew': H_2,
    'DInew': D_2,
    'rLznew': r_L_z_new,
    'gammanew': gamma_new,
    'aefnew': a_ef_new,
    'ksinew': ksi_new,
    'gnew': g_new,
    'vinew': v_new,
    'visnew': v_s_new,
    'Ttmaxnew': T_t_max_new,
    'Aznnew': A_new,
    'eprnew': eps_pr_new,
    'phionenew': phi_1_new,
    'phitwonew': phi_2_new,
    'aknew': a_k_new,
    'alnew': a_l_new,
    'asumnew': a_sum_new,
    'aefradnew':a_ef_rad_new,
    'Spnew':S_p_new,
    'binew': bi_new,
    'cinew': ci_new,
    'nrebranew':n_rebra_new,
    'hrebrnew': h_rebr_new,
    'GabV': V_r,
    'GabVnew':V_r_new,
    'deltaTpdop': delta_T_p_dop,
    'Kznewdva': K_z_new_2,
    'lambdaidop':lambda_i_dop,
}
